name: test_reg_env
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pandas
  - numpy
  - scikit-learn
  - scipy>=1.7.3
  - protobuf<=3.20.0
  - pip:
      - wandb==0.10.31
      - mlflow
      - pytest
