name: data_check_env
channels:
  - defaults
dependencies:
  - python=3.8
  - pandas
  - numpy
  - scipy>=1.7.3
  - protobuf<=3.20.0          # add this line
  - pip
  - pip:
      - wandb==0.10.31
      - mlflow
      - pytest

