name: basic_cleaning_env
channels:
  - defaults
dependencies:
  - python=3.8
  - pip=20.3.3
  - pandas=1.2.3
  - protobuf<=3.20.0           # <— add this line
  - pip:
      - wandb==0.10.31
      - mlflow
