name: train_rf_env
channels:
  - defaults
dependencies:
  - python=3.8
  - pip
  - pandas
  - numpy
  - scikit-learn
  - scipy
  - protobuf<=3.20.0       # avoid proto errors
  - pip:
      - wandb==0.10.31
      - mlflow
